#!/usr/bin/env bash
if [ "$1" = "sha256" ] && [ -n "$2" ]; then
if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$2" | awk '{print $1}'
else
    openssl dgst -sha256 -r "$2" | awk '{print $1}'
fi
else
    echo "Usage: mkhash sha256 <file>" >&2
    exit 1
fi